# Generated by Django 3.1.2 on 2020-11-22 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carro', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_producto', models.IntegerField(default='0')),
                ('cantidad_producto', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=99)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('catalogo', models.BooleanField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=99)),
                ('comuna', models.CharField(max_length=99)),
                ('provincia', models.CharField(max_length=99)),
                ('region', models.CharField(max_length=99)),
                ('fecha_nacimiento', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sexo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=99)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_periodo', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_boleta', models.IntegerField()),
                ('total_periodo', models.IntegerField()),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtv.boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=99)),
                ('nota', models.CharField(max_length=200)),
                ('total', models.IntegerField(default='0')),
                ('id_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtv.carro')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtv.producto'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mtv.orden'),
        ),
    ]
